; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -passes=slp-vectorizer -S -mtriple=riscv64 -mcpu=sifive-x280o < %s | FileCheck %s --check-prefixes=X280

;  t0 = A0[s0 & 0xff] ^ A1[(s1 >> 8) & 0xff] ^ A2[(s2 >> 16) & 0xff] ^ A3[s3 >> 24];
;  t1 = A0[s1 & 0xff] ^ A1[(s2 >> 8) & 0xff] ^ A2[(s3 >> 16) & 0xff] ^ A3[s0 >> 24];
;  t2 = A0[s2 & 0xff] ^ A1[(s3 >> 8) & 0xff] ^ A2[(s0 >> 16) & 0xff] ^ A3[s1 >> 24];
;  t3 = A0[s3 & 0xff] ^ A1[(s0 >> 8) & 0xff] ^ A2[(s1 >> 16) & 0xff] ^ A3[s2 >> 24];

@A0 = external hidden unnamed_addr constant [256 x i32], align 8
@A1 = external hidden unnamed_addr constant [256 x i32], align 8
@A2 = external hidden unnamed_addr constant [256 x i32], align 8
@A3 = external hidden unnamed_addr constant [256 x i32], align 8

define void @foo(ptr readonly %in_block, ptr writeonly %out_block) {
  %arrayidx1 = getelementptr inbounds nuw i8, ptr %in_block, i64 4
  %arrayidx2 = getelementptr inbounds nuw i8, ptr %in_block, i64 8
  %arrayidx3 = getelementptr inbounds nuw i8, ptr %in_block, i64 12

  %s0 = load i32, ptr %in_block, align 4
  %s1 = load i32, ptr %arrayidx1, align 4
  %s2 = load i32, ptr %arrayidx2, align 4
  %s3 = load i32, ptr %arrayidx3, align 4

  %and00 = and i32 %s0, 255
  %and01 = and i32 %s1, 255
  %and02 = and i32 %s2, 255
  %and03 = and i32 %s3, 255
  %idxprom00 = zext nneg i32 %and00 to i64
  %idxprom01 = zext nneg i32 %and01 to i64
  %idxprom02 = zext nneg i32 %and02 to i64
  %idxprom03 = zext nneg i32 %and03 to i64
  %arrayidx00 = getelementptr inbounds nuw [4 x i8], ptr @A0, i64 %idxprom00
  %arrayidx01 = getelementptr inbounds nuw [4 x i8], ptr @A0, i64 %idxprom01
  %arrayidx02 = getelementptr inbounds nuw [4 x i8], ptr @A0, i64 %idxprom02
  %arrayidx03 = getelementptr inbounds nuw [4 x i8], ptr @A0, i64 %idxprom03
  %t00 = load i32, ptr %arrayidx00, align 4
  %t01 = load i32, ptr %arrayidx01, align 4
  %t02 = load i32, ptr %arrayidx02, align 4
  %t03 = load i32, ptr %arrayidx03, align 4

  %shr10 = lshr i32 %s1, 8
  %shr11 = lshr i32 %s2, 8
  %shr12 = lshr i32 %s3, 8
  %shr13 = lshr i32 %s0, 8
  %and10 = and i32 %shr10, 255
  %and11 = and i32 %shr11, 255
  %and12 = and i32 %shr12, 255
  %and13 = and i32 %shr13, 255
  %idxprom10 = zext nneg i32 %and10 to i64
  %idxprom11 = zext nneg i32 %and11 to i64
  %idxprom12 = zext nneg i32 %and12 to i64
  %idxprom13 = zext nneg i32 %and13 to i64
  %arrayidx10 = getelementptr inbounds nuw [4 x i8], ptr @A1, i64 %idxprom10
  %arrayidx11 = getelementptr inbounds nuw [4 x i8], ptr @A1, i64 %idxprom11
  %arrayidx12 = getelementptr inbounds nuw [4 x i8], ptr @A1, i64 %idxprom12
  %arrayidx13 = getelementptr inbounds nuw [4 x i8], ptr @A1, i64 %idxprom13
  %t10 = load i32, ptr %arrayidx10, align 4
  %t11 = load i32, ptr %arrayidx11, align 4
  %t12 = load i32, ptr %arrayidx12, align 4
  %t13 = load i32, ptr %arrayidx13, align 4

  %shr20 = lshr i32 %s2, 16
  %shr21 = lshr i32 %s3, 16
  %shr22 = lshr i32 %s0, 16
  %shr23 = lshr i32 %s1, 16
  %and20 = and i32 %shr20, 255
  %and21 = and i32 %shr21, 255
  %and22 = and i32 %shr22, 255
  %and23 = and i32 %shr23, 255
  %idxprom20 = zext nneg i32 %and20 to i64
  %idxprom21 = zext nneg i32 %and21 to i64
  %idxprom22 = zext nneg i32 %and22 to i64
  %idxprom23 = zext nneg i32 %and23 to i64
  %arrayidx20 = getelementptr inbounds nuw [4 x i8], ptr @A2, i64 %idxprom20
  %arrayidx21 = getelementptr inbounds nuw [4 x i8], ptr @A2, i64 %idxprom21
  %arrayidx22 = getelementptr inbounds nuw [4 x i8], ptr @A2, i64 %idxprom22
  %arrayidx23 = getelementptr inbounds nuw [4 x i8], ptr @A2, i64 %idxprom23
  %t20 = load i32, ptr %arrayidx20, align 4
  %t21 = load i32, ptr %arrayidx21, align 4
  %t22 = load i32, ptr %arrayidx22, align 4
  %t23 = load i32, ptr %arrayidx23, align 4

  %shr30 = lshr i32 %s3, 24
  %shr31 = lshr i32 %s0, 24
  %shr32 = lshr i32 %s1, 24
  %shr33 = lshr i32 %s2, 24
  %and30 = and i32 %shr30, 255
  %and31 = and i32 %shr31, 255
  %and32 = and i32 %shr32, 255
  %and33 = and i32 %shr33, 255
  %idxprom30 = zext nneg i32 %and30 to i64
  %idxprom31 = zext nneg i32 %and31 to i64
  %idxprom32 = zext nneg i32 %and32 to i64
  %idxprom33 = zext nneg i32 %and33 to i64
  %arrayidx30 = getelementptr inbounds nuw [4 x i8], ptr @A3, i64 %idxprom30
  %arrayidx31 = getelementptr inbounds nuw [4 x i8], ptr @A3, i64 %idxprom31
  %arrayidx32 = getelementptr inbounds nuw [4 x i8], ptr @A3, i64 %idxprom32
  %arrayidx33 = getelementptr inbounds nuw [4 x i8], ptr @A3, i64 %idxprom33
  %t30 = load i32, ptr %arrayidx30, align 4
  %t31 = load i32, ptr %arrayidx31, align 4
  %t32 = load i32, ptr %arrayidx32, align 4
  %t33 = load i32, ptr %arrayidx33, align 4

  %p01 = xor i32 %t00, %t10;
  %p02 = xor i32 %p01, %t20;
  %p0 = xor i32 %p02, %t30;

  %p11 = xor i32 %t01, %t11;
  %p12 = xor i32 %p11, %t21;
  %p1 = xor i32 %p12, %t31;

  %p21 = xor i32 %t02, %t12;
  %p22 = xor i32 %p21, %t22;
  %p2 = xor i32 %p22, %t32;

  %p31 = xor i32 %t03, %t13;
  %p32 = xor i32 %p31, %t23;
  %p3 = xor i32 %p32, %t33;

  %arrayidxe1 = getelementptr inbounds nuw i8, ptr %out_block, i64 4
  %arrayidxe2 = getelementptr inbounds nuw i8, ptr %out_block, i64 8
  %arrayidxe3 = getelementptr inbounds nuw i8, ptr %out_block, i64 12

  store i32 %p0, ptr %out_block, align 4
  store i32 %p1, ptr %arrayidxe1, align 4
  store i32 %p2, ptr %arrayidxe2, align 4
  store i32 %p3, ptr %arrayidxe3, align 4
  ret void
}
